name: dbt CI

on:
  pull_request:
    branches:
      - master

jobs:
  dbt-run:
    runs-on: ubuntu-latest
    environment: DBT_BTC
    env:
      BRANCH_NAME: ${{ github.ref_name || github.head_ref  }}  # PR vs push

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Decide DBT_TARGET from branch
        shell: bash
        run: |
          echo "BRANCH_NAME=$BRANCH_NAME"
          if [[ "$BRANCH_NAME" == "Main" || "$BRANCH_NAME" == "master" ]]; then
            TARGET=prod
          elif [[ "$BRANCH_NAME" == dev* ]]; then
            TARGET=dev
          else
            TARGET=dev
          fi
          echo "DBT_TARGET=$TARGET" | tee -a $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.10'

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core==1.9.4 dbt-snowflake==1.9.4


      - name: Set up dbt profile and private key
        run: |
          mkdir -p ~/.dbt
          echo "$DBT_PROFILES_YML" > ~/.dbt/profiles.yml
        env:
          DBT_PROFILES_YML: ${{ secrets.DBT_PROFILES_YML }}



      - name: Install dbt deps
        run: dbt deps

      - name: dbt debug
        run: dbt debug --target "${{ env.DBT_TARGET }}"

      - name: dbt run
        run: dbt run --target "${{ env.DBT_TARGET }}"
